// <auto-generated />
namespace Renacer.Nucleo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cambioHorario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambioHorario));
        
        string IMigrationMetadata.Id
        {
            get { return "201906200315593_cambioHorario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
