// <auto-generated />
namespace Renacer.Nucleo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class agregadomatriculasocio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregadomatriculasocio));
        
        string IMigrationMetadata.Id
        {
            get { return "201905272106314_agregado-matricula-socio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
