export const itemsSocio = [
   {
    title: 'Calendario',
    icon: 'fa-calendar',
    routerLink: 'evento/calendario/',
    selected: false,
    expanded: false,
    order: 100,
  },
  {
    title: 'Mis Datos',
    selected: false,
    routerLink: 'perfil',
    icon: 'fa-user',
    expanded: false,
    order: 800,
  },
  {
    title: 'Mis Eventos',
    selected: false,
    routerLink: 'eventos-socio',
    icon: 'fa fa-list',
    expanded: false,
    order: 800,
  },
  {
    title: 'Inscribirme Evento',
    selected: false,
    routerLink: 'inscripcion-socio',
    icon: 'fa fa-pencil',
    expanded: false,
    order: 800,
  },  
  {
    title: 'Mis Intereses',
    routerLink: 'intereses',
    icon: 'fa-users',
    selected: false,
    expanded: false,
    order: 500,
  },
  {
    title: 'Mis Pagos',
    routerLink: 'mis-pagos',
    icon: 'fa-money',    
    selected: false,
    expanded: false,
    order: 500,
  },
  {
    title: 'Donaciones',
    routerLink: 'donaciones',
    icon: 'fa-money',
    selected: false,
    expanded: false,
    order: 500,
  }
];
