export const itemsSocio = [
   {
    title: 'Calendario',
    icon: 'fa-calendar',
    routerLink: 'evento/calendario/',
    selected: false,
    expanded: false,
    order: 100,
  },
  {
    title: 'Mis Datos',
    selected: false,
    routerLink: 'perfil',
    icon: 'fa-user',
    expanded: false,
    order: 800,
  },
  {
    title: 'Mis Asistencias',
    selected: false,
    routerLink: 'inscripciones',
    icon: 'fa-pencil',
    expanded: false,
    order: 800,
  },
  {
    title: 'Mis Intereses',
    routerLink: 'intereses',
    icon: 'fa-users',
    selected: false,
    expanded: false,
    order: 500,
  },
  {
    title: 'Mis Pagos',
    routerLink: 'pagos',
    icon: 'fa-money',
    selected: false,
    expanded: false,
    order: 500,
  },
  {
    title: 'Donaciones',
    routerLink: 'pagos',
    icon: 'fa-money',
    selected: false,
    expanded: false,
    order: 500,
  }
];
